# Generated by Django 5.0.6 on 2025-09-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('jahon', 'Jahon'), ('uzbekiston', "O'zbekiston"), ('sport', 'Sport'), ('texnika', 'Fan-texnika')], default='uzbekiston', max_length=20),
        ),
    ]
